ARG REGISTRY
ARG WORKLOAD
FROM ${REGISTRY}/accord/${WORKLOAD}:latest

# RStudio boilerplate
EXPOSE 8787
WORKDIR /home
USER 490
ENTRYPOINT [ "/usr/lib/rstudio-server/bin/rserver", "--server-working-dir=/home", "--server-user=user", "--auth-minimum-user-id=490" ]
# /RStudio boilerplate
