FROM quay.io/accord/<workload>:latest
# NOTE: the workload container must be based on theia-jupyter-base

# Jupyter boilerplate
EXPOSE 8888
WORKDIR /home
USER 490
ENTRYPOINT [ "entrypoint-jupyter.sh" ]
# /Jupyter boilerplate
