FROM quay.io/accord/<workload>:latest
# NOTE: the workload container must be based on theia-jupyter-base

# Theia boilerplate
EXPOSE 3000
ENV SHELL=/bin/bash \
  THEIA_DEFAULT_PLUGINS=local-dir:/usr/local/theia/plugins \
  USE_LOCAL_GIT=true
WORKDIR /usr/local/theia
USER 490
ENTRYPOINT [ "node", "/usr/local/theia/src-gen/backend/main.js", "/home", "--hostname=0.0.0.0" ]
# /Theia boilerplate
