FROM quay.io/accord/<workload>:latest
# NOTE: the workload container must be based on rstudio-base

# RStudio boilerplate
EXPOSE 8787
ENV USER=user
WORKDIR /home
USER 490
ENTRYPOINT [ "entrypoint-rstudio.sh" ]
# /RStudio boilerplate
