---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyter
  name: jupyter
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      volumes:
      - name: nfs-user
        nfs: 
          server: 192.168.86.105
          path: /home/parse
          readOnly: false
      - name: nfs-project
        nfs: 
          server: 192.168.86.105
          path: /home/project
          readOnly: false
      - name: jupyter-home
        emptyDir: {}
      containers:
      - image: registry.portal.linuxjedi.org/accord/jupyter:latest
        name: jupyter
        imagePullPolicy: Always
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        volumeMounts:
        - mountPath: /home/home
          name: nfs-user
        - mountPath: /home/project
          name: nfs-project
        - mountPath: /home/jovyan
          name: jupyter-home
      imagePullSecrets:
      - name: local-reg
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter
  name: jupyter
  namespace: admin
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jupyter
  namespace: admin
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
spec:
  rules:
    - host: jupyter.portal.linuxjedi.org
      http:
        paths:
          - path: /
            backend:
              serviceName: jupyter
              servicePort: 80
