FROM quay.io/accord/rstudio-base:latest

# No changes for rstudio-r

# RStudio boilerplate
EXPOSE 8787
ENV USER=user
WORKDIR /home
USER 490
ENTRYPOINT [ "entrypoint-rstudio.sh" ]
# /RStudio boilerplate
