FROM lnxjedi/gopherbot:amazon

ARG kubectlvers=v1.18.6

USER root

RUN pip3 install awscli kubernetes && \
    curl -L -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${kubectlvers}/bin/linux/amd64/kubectl && \
    chmod +x /usr/local/bin/kubectl && \
    mkdir -p /sbin/.vscode-server && \
    chown 2:root /sbin/.vscode-server && \
    chmod u+rwx /sbin/.vscode-server

# For amazonlinux, 2 == daemon. Numeric value needed for Kubernetes runAsNonRoot.
USER 2
