FROM lnxjedi/gopherbot:amazon

ARG kubectlvers=v1.18.6

USER root

RUN pip3 install awscli kubernetes && \
    curl -L -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${kubectlvers}/bin/linux/amd64/kubectl && \
    chmod +x /usr/local/bin/kubectl

# For amazonlinux, 2 == daemon. Numeric value needed for Kubernetes runAsNonRoot.
USER 2
